
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'brace_final brace_inicio bracket_final bracket_inicio coma dos_puntos numero textoJSON : brace_inicio BOOKS brace_finalBOOKS : texto dos_puntos bracket_inicio BOOK_LIST bracket_finalBOOK_LIST : brace_inicio BOOK_ENTRIES brace_finalBOOK_ENTRIES : BOOK_ENTRY\n                    | BOOK_ENTRY coma BOOK_ENTRIESBOOK_ENTRY : TITLE\n                  | AUTHOR\n                  | GENRE\n                  | PUBLICATION\n                  | ISBN\n                  | CHARACTERS\n                  | REVIEWSTITLE : texto dos_puntos texto comaAUTHOR : texto dos_puntos brace_inicio AUTHOR_DETAILS brace_final comaSTRING : texto dos_puntos textoINT : texto dos_puntos numeroAUTHOR_DETAILS : STRING coma INT coma STRINGGENRE : texto dos_puntos bracket_inicio texto coma texto bracket_final comaPUBLICATION : texto dos_puntos brace_inicio STRING coma INT coma STRING brace_final comaISBN : texto dos_puntos brace_inicio STRING coma STRING brace_final comaCHARACTERS : texto dos_puntos bracket_inicio CHARACTER_ENTRIES bracket_final comaCHARACTER_ENTRIES : CHARACTER_ENTRY coma CHARACTER_ENTRYCHARACTER_ENTRY : brace_inicio STRING coma STRING brace_finalREVIEWS : texto dos_puntos bracket_inicio REVIEW_ENTRIES bracket_finalREVIEW_ENTRIES : REVIEW_ENTRY coma REVIEW_ENTRYREVIEW_ENTRY : brace_inicio INT coma STRING brace_final'
    
_lr_action_items = {'brace_inicio':([0,7,23,27,44,45,],[2,9,26,37,57,59,]),'$end':([1,5,],[0,-1,]),'texto':([2,9,22,23,26,27,37,38,40,41,57,59,60,61,62,63,65,],[4,20,20,25,29,32,48,49,51,54,29,67,29,29,49,49,29,]),'brace_final':([3,10,11,12,13,14,15,16,17,18,19,24,28,30,43,49,50,52,55,68,69,71,72,73,78,],[5,-2,21,-4,-6,-7,-8,-9,-10,-11,-12,-5,-13,39,-24,-15,-14,64,-21,75,76,-20,77,-18,-19,]),'dos_puntos':([4,20,29,48,51,67,],[6,23,38,62,63,74,]),'bracket_inicio':([6,23,],[7,27,]),'bracket_final':([8,21,33,34,54,56,58,75,76,],[10,-3,42,43,66,-22,-25,-23,-26,]),'coma':([12,13,14,15,16,17,18,19,25,28,31,32,35,36,39,42,43,46,47,49,50,53,55,64,66,70,71,73,75,76,77,78,],[22,-6,-7,-8,-9,-10,-11,-12,28,-13,40,41,44,45,50,55,-24,60,61,-15,-14,65,-21,71,73,-16,-20,-18,-23,-26,78,-19,]),'numero':([62,63,74,],[70,70,70,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'JSON':([0,],[1,]),'BOOKS':([2,],[3,]),'BOOK_LIST':([7,],[8,]),'BOOK_ENTRIES':([9,22,],[11,24,]),'BOOK_ENTRY':([9,22,],[12,12,]),'TITLE':([9,22,],[13,13,]),'AUTHOR':([9,22,],[14,14,]),'GENRE':([9,22,],[15,15,]),'PUBLICATION':([9,22,],[16,16,]),'ISBN':([9,22,],[17,17,]),'CHARACTERS':([9,22,],[18,18,]),'REVIEWS':([9,22,],[19,19,]),'AUTHOR_DETAILS':([26,],[30,]),'STRING':([26,37,40,57,60,61,65,],[31,46,52,46,68,69,72,]),'CHARACTER_ENTRIES':([27,],[33,]),'REVIEW_ENTRIES':([27,],[34,]),'CHARACTER_ENTRY':([27,44,],[35,56,]),'REVIEW_ENTRY':([27,45,],[36,58,]),'INT':([37,40,59,],[47,53,47,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> JSON","S'",1,None,None,None),
  ('JSON -> brace_inicio BOOKS brace_final','JSON',3,'p_JSON','yaccCopy.py',6),
  ('BOOKS -> texto dos_puntos bracket_inicio BOOK_LIST bracket_final','BOOKS',5,'p_books','yaccCopy.py',10),
  ('BOOK_LIST -> brace_inicio BOOK_ENTRIES brace_final','BOOK_LIST',3,'p_book_lis','yaccCopy.py',14),
  ('BOOK_ENTRIES -> BOOK_ENTRY','BOOK_ENTRIES',1,'p_book_entries','yaccCopy.py',18),
  ('BOOK_ENTRIES -> BOOK_ENTRY coma BOOK_ENTRIES','BOOK_ENTRIES',3,'p_book_entries','yaccCopy.py',19),
  ('BOOK_ENTRY -> TITLE','BOOK_ENTRY',1,'p_book_entry','yaccCopy.py',26),
  ('BOOK_ENTRY -> AUTHOR','BOOK_ENTRY',1,'p_book_entry','yaccCopy.py',27),
  ('BOOK_ENTRY -> GENRE','BOOK_ENTRY',1,'p_book_entry','yaccCopy.py',28),
  ('BOOK_ENTRY -> PUBLICATION','BOOK_ENTRY',1,'p_book_entry','yaccCopy.py',29),
  ('BOOK_ENTRY -> ISBN','BOOK_ENTRY',1,'p_book_entry','yaccCopy.py',30),
  ('BOOK_ENTRY -> CHARACTERS','BOOK_ENTRY',1,'p_book_entry','yaccCopy.py',31),
  ('BOOK_ENTRY -> REVIEWS','BOOK_ENTRY',1,'p_book_entry','yaccCopy.py',32),
  ('TITLE -> texto dos_puntos texto coma','TITLE',4,'p_title','yaccCopy.py',36),
  ('AUTHOR -> texto dos_puntos brace_inicio AUTHOR_DETAILS brace_final coma','AUTHOR',6,'p_author','yaccCopy.py',40),
  ('STRING -> texto dos_puntos texto','STRING',3,'p_txt','yaccCopy.py',44),
  ('INT -> texto dos_puntos numero','INT',3,'p_int','yaccCopy.py',48),
  ('AUTHOR_DETAILS -> STRING coma INT coma STRING','AUTHOR_DETAILS',5,'p_author_details','yaccCopy.py',52),
  ('GENRE -> texto dos_puntos bracket_inicio texto coma texto bracket_final coma','GENRE',8,'p_genre','yaccCopy.py',56),
  ('PUBLICATION -> texto dos_puntos brace_inicio STRING coma INT coma STRING brace_final coma','PUBLICATION',10,'p_publication','yaccCopy.py',60),
  ('ISBN -> texto dos_puntos brace_inicio STRING coma STRING brace_final coma','ISBN',8,'p_isbn','yaccCopy.py',64),
  ('CHARACTERS -> texto dos_puntos bracket_inicio CHARACTER_ENTRIES bracket_final coma','CHARACTERS',6,'p_characters','yaccCopy.py',68),
  ('CHARACTER_ENTRIES -> CHARACTER_ENTRY coma CHARACTER_ENTRY','CHARACTER_ENTRIES',3,'p_character_entries','yaccCopy.py',72),
  ('CHARACTER_ENTRY -> brace_inicio STRING coma STRING brace_final','CHARACTER_ENTRY',5,'p_character_entry','yaccCopy.py',76),
  ('REVIEWS -> texto dos_puntos bracket_inicio REVIEW_ENTRIES bracket_final','REVIEWS',5,'p_reviews','yaccCopy.py',80),
  ('REVIEW_ENTRIES -> REVIEW_ENTRY coma REVIEW_ENTRY','REVIEW_ENTRIES',3,'p_review_entries','yaccCopy.py',84),
  ('REVIEW_ENTRY -> brace_inicio INT coma STRING brace_final','REVIEW_ENTRY',5,'p_review_entry','yaccCopy.py',88),
]
